/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.emi;

import com.emi.Interfaces.RunnableScreen;

import java.awt.Frame;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;


import java.awt.event.ActionEvent;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JLabel;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;


/**
 *
 * @author ME1
 */
public class log extends javax.swing.JFrame implements RunnableScreen {

    /**
     * Creates new form login
     */
	String Email;
	int a;

	forgetPass f= new forgetPass();
	private JLabel jLabel;
	private JLabel jLabel20;
	private JLabel invalidpass;
	private JPanel signuppanel;
	private JPanel panel;
	
	
    public log() {
        initComponents();
		email.setBackground(new Color(0,0,0,1));
		mdp.setBackground(new Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	Sign_In signup = new Sign_In();
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jPanel2 = new JPanel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        email = new javax.swing.JTextField();
        email.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyTyped(KeyEvent e) {
        		
        	}
        });
        jLabel6 = new JLabel();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        mdp = new javax.swing.JPasswordField();
        jLabel9 = new JLabel();
        disable = new JLabel();
        show = new JLabel();
        jLabel = new JLabel();
        panel = new JPanel();
        jLabel20 = new JLabel();
        invalidpass = new JLabel();
        jLabel.setFont(new Font("Segoe UI Semibold", Font.PLAIN, 12));
        jLabel11 = new JLabel();
        
        jLabel11.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
                jLabel11.setForeground(new Color(0, 0, 0));
        	}
        	@Override
        	public void mouseExited(MouseEvent e) {
                jLabel11.setForeground(new Color(199, 226, 255));
        	}
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		f.setVisible(true);
        	}
        });
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				registerUser();
			}
			private void registerUser() {
		        Email = email.getText();
				String password = String.valueOf(mdp.getPassword());
		        if(Email.isEmpty() && password.isEmpty())
		        {
		        	jLabel.setVisible(false);
		        	jLabel20.setVisible(true);
		        	invalidpass.setVisible(true);
		        }
		        else if (Email.isEmpty()) 
		        {
		        	jLabel.setVisible(false);
		        	invalidpass.setVisible(false);
		        	jLabel20.setVisible(true);
		        }
		        else if (password.isEmpty())
		        {
		        	jLabel.setVisible(false);
		        	jLabel20.setVisible(false);
		        	invalidpass.setVisible(true);		        	
		        }
		        else 
		        {
		        	a=Terrain.Login(Email,password);
		        	if (a!=0)
		        	{
		        		Register();
		        	}
		        	else
		        	{
			        	jLabel20.setVisible(false);
			        	invalidpass.setVisible(false);
		        		jLabel.setVisible(true);
		        	}
		        }
		}});
        jLabel13 = new JLabel();
        jLabel13.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		signup.setVisible(true);
        	}
        	@Override
        	public void mouseEntered(MouseEvent e) {
        		jLabel13.setForeground(new Color(0,0,0));
        	}
        	public void mouseExited(MouseEvent e) {
                jLabel13.setForeground(new Color(255, 255, 255));
        	}
        });
        jLabel14 = new JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bg-login.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 500, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 440));

        jPanel2.setBackground(new Color(25, 118, 211));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        panel.setBackground(new Color(30, 200, 200));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 40, 29));

        jLabel3.setFont(new Font("Segoe UI", 0, 32)); // NOI18N
        jLabel3.setForeground(new Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 420, 41));

        jLabel4.setFont(new Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setForeground(new Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hello! Let's get started");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 94, 420, -1));

        jLabel5.setFont(new Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new Color(199, 226, 255));
        jLabel5.setText("Email");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 123, 341, -1));

        email.setFont(email.getFont().deriveFont(email.getFont().getSize()+2f));
        email.setForeground(new Color(255, 255, 255));
        email.setBorder(null);
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 140, 240, 30));
        

        jLabel6.setForeground(new Color(255, 255, 255));
        jLabel6.setText("_________________________________________");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 147, 290, 39));

        jLabel.setForeground(Color.RED);
        jLabel.setText("Invalid Email or Password");
        jPanel2.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 255, 200, 39));
        jLabel.setVisible(false);
        
        jLabel20.setForeground(Color.RED);
        jLabel20.setText("Please Fill The Email Field");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 165, 200, 39));
        jLabel20.setVisible(false);
        
        invalidpass.setForeground(Color.RED);
        invalidpass.setText("Please Fill The Password Field");
        jPanel2.add(invalidpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 235, 200, 39));
        invalidpass.setVisible(false);
        
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_user_20px_1.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 147, 40, 39));

        jLabel8.setFont(new Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setForeground(new Color(199, 226, 255));
        jLabel8.setText("Password");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 192, 341, -1));
        
        
        
        mdp.setFont(mdp.getFont().deriveFont(mdp.getFont().getSize()+2f));
        mdp.setForeground(new Color(255, 255, 255));
        mdp.setBorder(null);
        mdp.setCaretColor(new Color(255, 255, 255));
        jPanel2.add(mdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 240, 30));

        jLabel9.setForeground(new Color(255, 255, 255));
        jLabel9.setText("_________________________________________");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 216, 290, 40));

        disable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_invisible_20px_1.png"))); // NOI18N
        disable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disable.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        jPanel2.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 216, 40, 40));

        show.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_eye_20px_1.png"))); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel2.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 216, 40, 40));


        jLabel11.setFont(new Font("Segoe UI", 0, 13)); // NOI18N
        jLabel11.setForeground(new Color(199, 226, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Forget Password?");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 261, 121, 27));

        jButton1.setBackground(new Color(255, 255, 255));
        jButton1.setFont(new Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new Color(25, 118, 211));
        jButton1.setText("LOGIN");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 306, 341, 40));

        jLabel13.setFont(new Font("Segoe UI", 0, 13)); // NOI18N
        jLabel13.setForeground(new Color(255, 255, 255));
        jLabel13.setText("Sign Up");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 357, 122, -1));

        jLabel14.setFont(new Font("Segoe UI", 0, 13)); // NOI18N
        jLabel14.setForeground(new Color(199, 226, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Don't have an account?");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 357, 213, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 420, 440));
        
        
        setSize(new java.awt.Dimension(916, 438));
        setLocationRelativeTo(null);
        InputMap inputMap = jButton1.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        // Get the action map for the button
        ActionMap actionMap = jButton1.getActionMap();

        // Define a key stroke for the shortcut
        KeyStroke keyStroke = KeyStroke.getKeyStroke("Enter");

        // Add the shortcut to the input map
        inputMap.put(keyStroke, "doClick");

        // Add the action to the action map
        actionMap.put("doClick", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                // Code to be executed when the shortcut is pressed
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void disableMouseClicked(MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        mdp.setEchoChar((char)0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setEnabled(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void showMouseClicked(MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        mdp.setEchoChar((char)8226);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setEnabled(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked
    public void Register()
    {
    	Home h = new Home(this);
    	h.setAdmin(a);
		h.SetName(Terrain.user(Email));
		h.setVisible(true);
		this.setVisible(false);
		h.setMail(Email);
    	jLabel.setVisible(false);
    	jLabel20.setVisible(false);
    	invalidpass.setVisible(false);
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <=1.0; i = i+0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(50);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_formWindowOpened
    
    public String GetMail()
    {
    	return Email;
    }
    public int GetLog()
    {
    	return a;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel disable;
    private javax.swing.JButton jButton1;
    private JLabel jLabel1;
    private JLabel jLabel11;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JLabel show;
    private javax.swing.JPasswordField mdp;
    private javax.swing.JTextField email;
    // End of variables declaration//GEN-END:variables
	@Override
	public void run() {
		try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new log().setVisible(true);
            }
        });
	}
}
