/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.emi;

import com.emi.Interfaces.RunnableScreen;

import java.awt.Frame;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;

import java.awt.event.ActionEvent;
import javax.swing.SwingConstants;


import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;


/**
 *
 * @author ME1
 */
public class Sign_In extends javax.swing.JFrame implements RunnableScreen {

    private JLabel FirstName;
	private JLabel LastName;
	private JLabel Adress;
	private JLabel City;
	private JLabel Phone;
	private JLabel Year;
	private JLabel Day;
	private JLabel Month;
	private JTextField FirstNamef;
	private JTextField LastNamef;
	private JLabel jLabel20;
	private JLabel jLabel21;
	private JPasswordField mdpc;
	private JLabel jLabel22;
	private JLabel jLabel23;
	private JLabel jLabel24;
	private JTextField adress;
	private JLabel jLabel25;
	private JTextField phone;
	private JLabel jLabel26;
	private JTextField city;
	private JSpinner day;
	private JSpinner month;
	private JLabel Cancel;
	/**
     * Creates new form login
     */
	
    public Sign_In() {
        initComponents();
		email.setBackground(new Color(0,0,0,1));
		mdp.setBackground(new Color(0,0,0,1));
		FirstNamef.setBackground(new Color(0,0,0,1));
		LastNamef.setBackground(new Color(0,0,0,1));
		mdpc.setBackground(new Color(0,0,0,1));
		adress.setBackground(new Color(0,0,0,1));
		phone.setBackground(new Color(0,0,0,1));
		city.setBackground(new Color(0,0,0,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new JLabel();
        jLabel1.setIcon(new ImageIcon("D:\\Games\\depositphotos_515228814-stock-illustration-online-registration-sign-login-account_1_500x400.jpg"));
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel5 = new JLabel();
        FirstName = new JLabel();
        LastName = new JLabel();
        jLabel20 = new JLabel();
        jLabel21 = new JLabel();
        jLabel22 = new JLabel();
        jLabel23 = new JLabel();
        adress = new JTextField();
        FirstNamef = new JTextField();
        LastNamef= new JTextField();
        Adress = new JLabel();
        City = new JLabel();
        Phone = new JLabel();
        Year = new JLabel();
        Day = new JLabel();
        Month = new JLabel();
        year = new JSpinner();
        day = new JSpinner();
        month = new JSpinner();
        email = new JTextField();
        city = new JTextField();
        phone = new JTextField();
        jLabel6 = new JLabel();
        jLabel8 = new JLabel();
        mdp = new JPasswordField();
        mdpc = new JPasswordField();
        jLabel24 = new JLabel();
        jLabel9 = new JLabel();
        disable = new JLabel();
        show = new JLabel();
        jLabel25 = new JLabel();
        jLabel26 = new JLabel();
        Cancel = new JLabel();
        
        Cancel.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseEntered(MouseEvent e) {
                Cancel.setForeground(new Color(0, 0, 0));
        	}
        	public void mouseExited(MouseEvent e)
        	{
        		Cancel.setForeground(new Color(255,255,255));
        	}
        	public void mouseClicked(MouseEvent evt) {
        		setVisible(false);
            }
        });
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	String test;
			public void actionPerformed(ActionEvent e) {
				registerUser();
			}
			private void registerUser() {
		        String Email = email.getText();
				String password = String.valueOf(mdp.getPassword());
				String prenom = FirstNamef.getText() ;
		        String nom = LastNamef.getText();
		        String passwordc = String.valueOf(mdp.getPassword());
		        int year1 = (int)year.getValue();
		        int day1 = (int)day.getValue();
		        int month1 = (int)month.getValue();
		        String city1 = city.getText();
		        String phone1 = phone.getText();
		        String adress1 = adress.getText();
		        String datenaiss = Integer.toString(day1)+"/"+Integer.toString(month1)+"/"+Integer.toString(year1);
		        if (Email.isEmpty())
		        {
		            jLabel6.setForeground(new Color(255, 0, 0));
		        }
		        else
		        {
		            jLabel6.setForeground(new Color(255, 255, 255));
		        }
		        if (password.isEmpty())
		        {
		            jLabel9.setForeground(new Color(255, 0, 0));
		        }
		        else
		        {
		            jLabel9.setForeground(new Color(255, 255, 255));
		        }
		        if (prenom.isEmpty())
		        {
		            jLabel20.setForeground(new Color(255, 0, 0));
		        }
		        else
		        {
		        	jLabel20.setForeground(new Color(255, 255, 255));
		        }
		        if (nom.isEmpty())
		        {
		            jLabel21.setForeground(new Color(255, 0, 0));
		        }
		        else
		        {
		        	jLabel21.setForeground(new Color(255, 255, 255));
		        }
		        if (passwordc.isEmpty())
		        {
		            jLabel23.setForeground(new Color(255, 0, 0));
		        }
		        else
		        {
		        	jLabel23.setForeground(new Color(255, 255, 255));
		        }
		        if (city1.isEmpty())
		        {
		            jLabel24.setForeground(new Color(255, 0, 0));
		        }
		        else
		        {
		        	jLabel24.setForeground(new Color(255, 255, 255));
		        }
		        if (phone1.isEmpty())
		        {
		            jLabel25.setForeground(new Color(255, 0, 0));
		        }
		        else
		        {
		        	jLabel25.setForeground(new Color(255, 255, 255));
		        }
		        if (adress1.isEmpty())
		        {
		            jLabel26.setForeground(new Color(255, 0, 0));
		        }
		        else
		        {
		        	jLabel26.setForeground(new Color(255, 255, 255));
		        }
		        if (!(Email.isEmpty() || password.isEmpty() || prenom.isEmpty() || nom.isEmpty() || passwordc.isEmpty() || city1.isEmpty() || phone1.isEmpty() || adress1.isEmpty()))
		        {
		        	if (password.compareTo(passwordc)==0)
		        	{
		        		if (Terrain.emailvalidation(Email)==true && Terrain.passwordvalidation(password)==true && Terrain.isValidFirstName(prenom)==true && Terrain.isValidLastName(nom)==true)
		        		{
			        		if(Terrain.SignUp(nom, prenom, Email, password, adress1, city1, phone1, datenaiss)==0)
			        		{
				        		JOptionPane.showMessageDialog(null, "Signed Up Successfully");
				        		dispose();
			        		}
			        		else
			        		{
				        		JOptionPane.showMessageDialog(null, "This Account Already Exist");
			        		}
		        		}
		        		else if(Terrain.emailvalidation(Email)==false)
		        		{
			        		JOptionPane.showMessageDialog(null, "Your Email Not Valid");
		        		}
		        		else if(Terrain.passwordvalidation(password))
		        		{
			        		JOptionPane.showMessageDialog(null, "Your Password Is Shorter Than 8 Characters");
		        		}
		        		else if(Terrain.isValidFirstName(prenom)==false)
		        		{
			        		JOptionPane.showMessageDialog(null, "Your First Name Is Not Valid");	
		        		}
		        		else if(Terrain.isValidLastName(nom)==false)
		        		{
			        		JOptionPane.showMessageDialog(null, "Your Last Name Is Not Valid");
		        		}
		        	}
		        	else
		        	{
			        	JOptionPane.showMessageDialog(null, "Password doesn't Match With Confirm Password");
		        	}
		        }
		}});


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 500, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 440));

        jPanel2.setBackground(new Color(25, 118, 211));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 40, 29));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel3.setForeground(new Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setText("Sign Up");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 420, 41));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setForeground(new Color(199, 226, 255));
        jLabel5.setText("Email");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 110, 341, -1));
        
        FirstName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        FirstName.setForeground(new Color(199, 226, 255));
        FirstName.setText("FirstName");
        jPanel2.add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 65, 100, -1));
        
        LastName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        LastName.setForeground(new Color(199, 226, 255));
        LastName.setText("LastName");
        jPanel2.add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 65, 100, -1));

        email.setFont(email.getFont().deriveFont(email.getFont().getSize()+2f));
        email.setForeground(new Color(255, 255, 255));
        email.setBorder(null);
        jPanel2.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 130, 240, 20));
        
        FirstNamef.setFont(FirstNamef.getFont().deriveFont(FirstNamef.getFont().getSize()+2f));
        FirstNamef.setForeground(new Color(255, 255, 255));
        FirstNamef.setBorder(null);
        jPanel2.add(FirstNamef, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 85, 100, 20));
        
        LastNamef.setFont(LastNamef.getFont().deriveFont(FirstNamef.getFont().getSize()+2f));
        LastNamef.setForeground(new Color(255, 255, 255));
        LastNamef.setBorder(null);
        jPanel2.add(LastNamef, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 85, 100, 20));
        
        jLabel20.setForeground(new Color(255, 255, 255));
        jLabel20.setText("______________");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 90, 100, 29));
        
        jLabel21.setForeground(new Color(255, 255, 255));
        jLabel21.setText("______________");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 100, 29));

        jLabel6.setForeground(new Color(255, 255, 255));
        jLabel6.setText("_________________________________________");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 135, 290, 29));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setForeground(new Color(199, 226, 255));
        jLabel8.setText("Password");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 155, 341, -1));

        mdp.setFont(mdp.getFont().deriveFont(mdp.getFont().getSize()+2f));
        mdp.setForeground(new Color(255, 255, 255));
        mdp.setBorder(null);
        mdp.setCaretColor(new Color(255, 255, 255));
        jPanel2.add(mdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 175, 240, 20));
        

        jLabel9.setForeground(new Color(255, 255, 255));
        jLabel9.setText("_________________________________________");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 185, 290, 20));
        
        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel22.setForeground(new Color(199, 226, 255));
        jLabel22.setText("Confirm Password");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 205, 341, -1));
        
        mdpc.setFont(mdpc.getFont().deriveFont(mdpc.getFont().getSize()+2f));
        mdpc.setForeground(new Color(255, 255, 255));
        mdpc.setBorder(null);
        mdpc.setCaretColor(new Color(255, 255, 255));
        jPanel2.add(mdpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 225, 240, 20));
        
        jLabel23.setForeground(new Color(255, 255, 255));
        jLabel23.setText("_________________________________________");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 235, 290, 20));
        
        Adress.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Adress.setForeground(new Color(199, 226, 255));
        Adress.setText("Adresse");
        jPanel2.add(Adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 255, 341, -1));
        
        adress.setFont(adress.getFont().deriveFont(adress.getFont().getSize()+2f));
        adress.setForeground(new Color(255, 255, 255));
        adress.setBorder(null);
        adress.setCaretColor(new Color(255, 255, 255));
        jPanel2.add(adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 275, 240, 20));
        
        jLabel24.setForeground(new Color(255, 255, 255));
        jLabel24.setText("_________________________________________");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 285, 290, 20));
        
        Phone.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Phone.setForeground(new Color(199, 226, 255));
        Phone.setText("PhoneNumber");
        jPanel2.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 305, 341, -1));
        
        phone.setFont(phone.getFont().deriveFont(phone.getFont().getSize()+2f));
        phone.setForeground(new Color(255, 255, 255));
        phone.setBorder(null);
        phone.setCaretColor(new Color(255, 255, 255));
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 325, 240, 20));
        
        jLabel25.setForeground(new Color(255, 255, 255));
        jLabel25.setText("_________________________________________");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 335, 290, 20));
        
        City.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        City.setForeground(new Color(199, 226, 255));
        City.setText("City");
        jPanel2.add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 355, 75, -1));
        
        city.setFont(city.getFont().deriveFont(city.getFont().getSize()+2f));
        city.setForeground(new Color(255, 255, 255));
        city.setBorder(null);
        jPanel2.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 375, 75, 20));
        
        jLabel26.setForeground(new Color(255, 255, 255));
        jLabel26.setText("___________");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 380, 80, 29));
        
        Day.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Day.setForeground(new Color(199, 226, 255));
        Day.setText("Day");
        jPanel2.add(Day, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 355, 75, -1));
        
		day.setForeground(Color.WHITE);
		day.setBackground(Color.BLACK);
		day.setModel(new SpinnerNumberModel(15, 1, 30, 1));
        jPanel2.add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 380, 50, 30));

        Year.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Year.setForeground(new Color(199, 226, 255));
        Year.setText("Year");
        jPanel2.add(Year, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 355, 75, -1));
        
		year.setForeground(Color.WHITE);
		year.setBackground(Color.BLACK);
		year.setModel(new SpinnerNumberModel(Integer.valueOf(2000), null, null, Integer.valueOf(1)));
        jPanel2.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 380, 70, 30));
        
        Month.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Month.setForeground(new Color(199, 226, 255));
        Month.setText("Month");
        jPanel2.add(Month, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 355, 75, -1));
        
        month.setForeground(Color.WHITE);
		month.setBackground(Color.BLACK);
		month.setModel(new SpinnerNumberModel(5,1,12,1));
        jPanel2.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 380, 50, 30));
        
        
        Cancel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Cancel.setForeground(new Color(255, 255, 255));
        Cancel.setText("Cancel");
        Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 410, 45, 15));

        disable.setHorizontalAlignment(SwingConstants.CENTER);
        disable.setIcon(new ImageIcon(getClass().getResource("/icon/icons8_invisible_20px_1.png"))); // NOI18N
        disable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disable.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        jPanel2.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 175, 40, 20));

        show.setHorizontalAlignment(SwingConstants.CENTER);
        show.setIcon(new ImageIcon(getClass().getResource("/icon/icons8_eye_20px_1.png"))); // NOI18N
        show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        jPanel2.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 175, 40, 20));

        jButton1.setBackground(new Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new Color(25, 118, 211));
        jButton1.setText("Sign Up");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 375, 90, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 420, 440));

        setSize(new java.awt.Dimension(916, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void disableMouseClicked(MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        mdp.setEchoChar((char)0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setEnabled(true);
        show.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void showMouseClicked(MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        mdp.setEchoChar((char)8226);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setEnabled(false);
        show.setEnabled(false);
    }//GEN-LAST:event_showMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <=1.0; i = i+0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(20);
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_formWindowOpened



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel disable;
    private javax.swing.JButton jButton1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private JLabel show;
    private JPasswordField mdp;
    private JTextField email;
    private JSpinner year;
    // End of variables declaration//GEN-END:variables
	@Override
	public void run() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_In().setVisible(true);
            }
        });
	}
}
